repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending
  - repo: https://github.com/crate-ci/typos
    rev: "typos-dict-v0.11.35"
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.3"
    hooks:
      - id: ruff
